#!/bin/bash
cd emmc
mkdir dev etc lib mnt proc root sbin sys tmp
find . | cpio -H newc -o | lzma >../uinit-emmc.cpio.gz
cd ..
mkimage -A arm -O linux -T ramdisk -C lzma -a 0 -e 0 -n 'SmilePlug eMMC Updater' -d uinit-emmc.cpio.gz uinit-emmc
